### ISSUE TITLE
addressing scheme

### ISSUE THREAD

**Issue by yanziqiang** [mic159/ArduinoMesh#1]
Hi Michael, really interested in using your mesh stack but I have few questions though....
1. is your topology truly MESH as opposed to RF24network's TREE?
2. what is the addressing scheme, do u segregate ranges for routing & non-routing nodes? I hope there's no segregation, ie. all are routing.
3. how many hexa digit for address? 0x0000h - 0xFFFFh ?
4. you have any website detailing the above and some sort of examples for all the capability of your stack?

Many thanks and look forward to your reply.
Merry X'mas and a happy new year!
~Gan

**Comment by mic159** [comment]
Hi Gan,

This is still very much a work in progress.
There is currently no MESH implementation included, but it is planned.

Yes, it will be mesh and not a tree network.
The addressing scheme is currently 0x00000000 - 0xFFFFFFFF, and by default all nodes will be routing, but with an option to turn it off.
No, there is currently no website or documentation because it is nowhere near finished.
You are welcome to help out if you want

-Mic

**Comment by yanziqiang** [comment]
Mic, i doubt i can help much as i'm very nooby in C/C++...and with the many
namespace reassignment all around the places, I'm having harder times
trying to understand... but i can try if u don't mind my noob questions...
as such in your code, how does the router function behave right now?

how many nodes are maintained in the peer list?

which function to call to set the addr for the node?
in your rftest.ino, i can't seem to find it....
in meshbase.cpp , i found the below, just can't find where is address(0) or
what it's doing...

On Sat, Dec 29, 2012 at 9:56 AM, Michael notifications@github.com wrote:

> Hi Gan,
> 
> This is still very much a work in progress.
> There is currently no MESH implementation included, but it is planned.
> 
> Yes, it will be mesh and not a tree network.
> The addressing scheme is currently 0x00000000 - 0xFFFFFFFF, and by default
> all nodes will be routing, but with an option to turn it off.
> No, there is currently no website or documentation because it is nowhere
> near finished.
> You are welcome to help out if you want
> 
> -Mic
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mic159/ArduinoMesh/issues/1#issuecomment-11746131.

## 

Regards,
 CK

**Comment by mic159** [comment]
Currently, it waits for 2 network discovery intervals and builds up a graph of the network, then chooses a random unused address. The code is in MeshBase::ChooseAddress().
That way you dont have to upload a different sketch to each node.
I would like for it to save the address in memory so it will remain the same after a reboot.

The router currently does not function. It has not been designed yet. Currently it can only see, know about, and send messages to direct nodes.
