### ISSUE TITLE
After running for awhile, I get multiple sends

### ISSUE THREAD

**Issue by justind000** [mic159/ArduinoMesh#2]
After running this for awhile, maybe an hour or so, I get the senders sending out multiple events. Maybe up to 5 or 6 extra events per interval tick.

**Comment by mic159** [comment]
Hmm, it could potentially be on the receiver end, where its not completely emptying the buffer each time, and the next packet causes it to realize that there is messages waiting.

**Comment by justind000** [comment]
My setup was two publishers and one subscriber. To duplicate just load the example and change the interval to 100 or so. Give it about 30 minutes and it so start to send doubles then triple and so on.
